name: tests

on:
  workflow_dispatch:
  push:
  pull_request:
concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-macos:
    runs-on: macos-latest
    steps:
      - name: Execute command
        run: pipx install --python 3.12 --fetch-missing-python --verbose ansible==9.5.1
